platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

inputs:
  - name: metrics-repo
  - name: version

outputs:
  - name: build  

run:
  path: metrics-repo/ci/tasks/build-artifact.sh
